### ISSUE TITLE
[Solved] How to compile the EvalSystem under Ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-Evaluation-System#1]
To pass compiling the 3.06 beta, the following problems should be dealed with, and all related to filenames. In Linux/Unix, the file names are case sensitive! Besides, using the latest toolchain from the ARM company, since the default arm toolchain in 18.04 LTS has a bug!
1. In boards/SelfTest_Landungsbruecke.c, 
    #include "board.h" should be #include "Board.h";
    #include "../tmc/vitalSignsMonitor.h" shuld be #include "../tmc/VitalSignsMonitor.h"
    #include "../tmc/idDetection.h" should be #include "../tmc/IdDetection.h"
2. In TMC/StepDir.h,
    	#include "../hal/hal.h" should be 	#include "../hal/HAL.h"
3. In main.c
    #include "tmc/idDetection.h" should be #include "tmc/IdDetection.h"

**Comment by trinamic-ed** [comment]
Thanks for the info. We will fix the naming issues.
