### ISSUE TITLE
How to check that how long some algorithm takes on Landungsbruecke board?

### ISSUE THREAD

**Issue by huskier** [trinamic/TMC-Evaluation-System#3]
We want to check that how long our own algorithm takes on Landungsbruecke board, and what's the simplest way to do this?

**Comment by trinamic-ed** [comment]
Hi, you can e.g. use an IO output pin and measure the time with an scope. Which time period do you want to measure? Maybee the systick millisecond counter can be used?

**Comment by huskier** [comment]
We want to measure the MainLoop's time period(In the main.c file).  We want to know the exact time period of periodicJob in the TMC4671_eval.c file. Also the exact time period of the tmc_linearRamp_computeRampPosition(...) and tmc_linearRamp_computeRampVelocity(...) function.

Besides, we'd like to make the RS232 work, so we could get information from the Landungsbruecke board. We reference your code, and write the following code. Could we get what we expect?  (Right now, we cannot do the experiments)

void txTest(RXTXTypeDef *RXTX)
{
	uint8 reply[2];
	reply[0] = 0;
	reply[1] = 1;
	RXTX->txN(reply, 2);
}

// somewhere to call the function......
txTest(&interfaces[1]);   //send 01 to Serial Port (CON_RS232)......
